---
- include_vars: vault.yml
- name: Install pacages and dependencies
  yum: name={{ item }} state=present
  with_items:
    - python
    - php
    - php-mysql
    - mysql-server
    - mysql
    - MySQL-python

- name: run MySQL
  service: name=mysqld state=started enabled=yes

- name: create db user
  mysql_user: name={{ mysql.user }} password={{ mysql.password }} host={{ mysql.host }} state=present priv={{ mysql.privileges }}

- name: create mysql database
  mysql_db: name={{ mysql.db }} state=present
