---
- name: Install dependencies
  yum: name={{ item }} state=present
  with_items:
    - python
    - httpd
    - php
    - php-mysql
    - php-gd
    - php-xml
    - mysql-server
    - mysql
    - wget
- name: Download MediaWiki
  get_url:
    url: "{{ download_url }}"
    dest: /tmp/mediawiki.tgz
    owner: "{{ wiki.user }}"
    group: "{{ wiki.user }}"
    mode: 0744

- name: Unarchive MediaWiki
  unarchive:
    src: /tmp/mediawiki.tgz
    dest: /tmp/
    remote_src: yes
    owner: "{{ wiki.user }}"
    group: "{{ wiki.user }}"
    
- name: Moving MediaWiki to web directory
  command: creates={{ wiki.install_dir }}/{{ filename }} mv /tmp/{{ filename }}/ {{ wiki.install_dir }}
    
- name: Create symbolic link 
  file:
    src: "{{ wiki.install_dir }}/{{ filename }}"
    dest: "{{ wiki.install_dir }}/mediawiki"
    state: link
    
- name: Taking backup of /etc/httpd/conf/httpd.conf
  copy:
    src: /etc/httpd/conf/httpd.conf
    dest: /etc/httpd/conf/httpd.conf.bkp
    
- name: Insert/update configuration block in /etc/httpd/conf/httpd.conf
  blockinfile:
    path: /etc/httpd/conf/httpd.conf
    block: |
      DocumentRoot "/var/www"
      <Directory "/var/www">
         Options FollowSymLinks
         AllowOverride None
      </Directory>
      DirectoryIndex index.html index.html.var index.php
