---
- name: Install dependencies
  yum: name={{ item }} state=present
  with_items:
    - python
    - httpd
    - php
    - php-mysql
    - php-gd
    - php-xml
    - mysql-server
    - mysql
    - wget
- name: Download MediaWiki
  get_url:
    url: "{{ download_url }}"
    dest: /tmp/mediawiki.tgz
    owner: "{{ wiki.user }}"
    group: "{{ wiki.user }}"
    mode: 0744

- name: Unarchive MediaWiki
  unarchive:
    src: /tmp/mediawiki.tgz
    dest: "{{ wiki.install_dir }}"
    remote_src: yes
    owner: "{{ wiki.user }}"
    group: "{{ wiki.user }}"
    
- name: Create symbolic link 
  file:
    src: "{{ wiki.install_dir }}/{{ filename }}"
    dest: "{{ wiki.install_dir }}/mediawiki"
    state: link
