---
- name: Install dependencies
  yum: name={{ item }} state=present
  with_items:
    - python
    - httpd
    - php
    - php-mysql
    - php-gd
    - php-xml
    - mysql-server
    - mysql
    - wget
- name: Download MediaWiki
  get_url:
    url: "http://releases.wikimedia.org/mediawiki/1.31/mediawiki-1.31.1.tar.gz"
    dest: /home/wiki/mediawiki.tgz
    owner: wiki
    group: wiki
    mode: 0744

- name: Unarchive MediaWiki
  unarchive:
    remote_src: yes
    src: /home/wiki/mediawiki.tgz
    dest: /home/wiki/
    owner: wiki
    group: wiki
